#Hayat White
#Class: capstone
#spring 2024

EXE = tomypeers
CFLAGS = -Wall
CXXFLAGS = -Wall
LDLIBS = 
CC = gcc

.PHONY: all
all: $(EXE)

peer: tomypeers.c
	$(CC) $(CFLAGS) tomypeers.c $(LDLIBS) -o tomypeers

.PHONY: clean
clean:
	rm -f $(EXE)

